
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

import java_cup.runtime.*;
import java.util.LinkedList;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class GSintactico extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return HSimbolos.class;
}

  /** Default constructor. */
  @Deprecated
  public GSintactico() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public GSintactico(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public GSintactico(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\002\000\002\002\004\000\002\002\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\004\000\004\004\004\001\002\000\004\002\000\001" +
    "\002\000\004\002\006\001\002\000\004\002\001\001\002" +
    "" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\004\000\004\002\004\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$GSintactico$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$GSintactico$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$GSintactico$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



	public String resultado = "";   //declaracion de variable que nos servira para imprimir el resultado
	public static LinkedList<THError> TablaES = new LinkedList<THError>();
	
	//Metodo al que se llama automaticamente ante algun error sintactico
	public void syntax_error(Symbol s)
	{
		String lexema = s.value.toString();
		int fila = s.right;
		int columna = s.left;
		
		System.out.println("!!!! Error Sintactico Recuperado");
		System.out.println("\t\tLexema: " + lexema);
		System.out.println("\t\tFila: " + fila);
		System.out.println("\t\tColumna: " + columna);
		
		THError datos = new THError(lexema, fila, columna, "Error sintactico", "El caracter no viene en lo esperado");
		TablaES.add(datos);
	}
	
	//metodo que se llama cuando ya no es posible recuperarse del error
	public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception
	{
		String lexema = s.value.toString();
		int fila = s.right;
		int columna = s.left;
		
		System.out.println("!!!! Error Sintactico, modo panico");
		System.out.println("\t\tLexema: " + lexema);
		System.out.println("\t\tFila: " + fila);
		System.out.println("\t\tColumna: " + columna);
		
		THError datos = new THError(lexema, fila, columna, "Error sintactico", "El caracter no viene en lo esperado");
		TablaES.add(datos);
		
	}


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$GSintactico$actions {




  private final GSintactico parser;

  /** Constructor */
  CUP$GSintactico$actions(GSintactico parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$GSintactico$do_action_part00000000(
    int                        CUP$GSintactico$act_num,
    java_cup.runtime.lr_parser CUP$GSintactico$parser,
    java.util.Stack            CUP$GSintactico$stack,
    int                        CUP$GSintactico$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$GSintactico$result;

      /* select the action based on the action number */
      switch (CUP$GSintactico$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= INICIO EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$GSintactico$stack.elementAt(CUP$GSintactico$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$GSintactico$stack.elementAt(CUP$GSintactico$top-1)).right;
		String start_val = (String)((java_cup.runtime.Symbol) CUP$GSintactico$stack.elementAt(CUP$GSintactico$top-1)).value;
		RESULT = start_val;
              CUP$GSintactico$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$GSintactico$stack.elementAt(CUP$GSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$GSintactico$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$GSintactico$parser.done_parsing();
          return CUP$GSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // INICIO ::= mas 
            {
              String RESULT =null;
		 System.out.println("entrada correcta"); 
              CUP$GSintactico$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$GSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$GSintactico$stack.peek()), RESULT);
            }
          return CUP$GSintactico$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$GSintactico$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$GSintactico$do_action(
    int                        CUP$GSintactico$act_num,
    java_cup.runtime.lr_parser CUP$GSintactico$parser,
    java.util.Stack            CUP$GSintactico$stack,
    int                        CUP$GSintactico$top)
    throws java.lang.Exception
    {
              return CUP$GSintactico$do_action_part00000000(
                               CUP$GSintactico$act_num,
                               CUP$GSintactico$parser,
                               CUP$GSintactico$stack,
                               CUP$GSintactico$top);
    }
}

}
